version: '3.8'

services:
  cloudflared-ssh:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared-ssh
    restart: always
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_SSH_TUNNEL_TOKEN}
      - TUNNEL_METRICS=0.0.0.0:60123
    network_mode: host
    deploy:
      resources:
        reservations:
          memory: 64M
        limits:
          memory: 256M
    mem_reservation: 64m
    mem_limit: 256m
    oom_score_adj: -900
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    healthcheck:
      test: ["CMD", "cloudflared", "tunnel", "--metrics", "localhost:60123", "ready"]
      interval: 30s
      timeout: 30s
      retries: 3