#!/bin/bash
# Report for livekit

echo
echo "================================= LiveKit ============================="
echo
echo "Real-time Voice & Video Infrastructure (WebRTC SFU Server)"
echo
echo "WebSocket URL: wss://${LIVEKIT_HOSTNAME:-<hostname_not_set>}"
echo
echo "API Credentials (for client authentication):"
echo "  API Key: ${LIVEKIT_API_KEY:-<not_set_in_env>}"
echo "  API Secret: ${LIVEKIT_API_SECRET:-<not_set_in_env>}"
echo
echo "Access:"
echo "  External WebSocket: wss://${LIVEKIT_HOSTNAME:-<hostname_not_set>}"
echo "  Internal WebSocket: ws://livekit-server:7880"
echo "  Internal HTTP API: http://livekit-server:7881"
echo
echo "⚠️  CRITICAL NETWORK REQUIREMENTS:"
echo "  - UDP Ports 50000-50100 MUST be open for WebRTC media"
echo "  - TCP Port 7882 required for fallback"
echo "  - Without UDP: Audio/Video will NOT work!"
echo
echo "Network Configuration:"
echo "  Media Ports: 50000-50100/udp + 7882/tcp"
echo "  Node IP: ${JVB_DOCKER_HOST_ADDRESS:-<auto-detected>}"
echo
echo "Authentication:"
echo "  ✓ JWT-based client authentication (no login UI)"
echo "  ✓ Generate tokens using API Key/Secret"
echo "  ✓ Tokens must be generated by your backend/n8n"
echo
echo "n8n Integration:"
echo "  1. Install LiveKit SDK: npm install livekit-server-sdk"
echo "  2. Generate access tokens using API Key/Secret"
echo "  3. Pass tokens to frontend/client applications"
echo "  4. Use internal URL: ws://livekit-server:7880"
echo
echo "Client SDKs Available:"
echo "  - JavaScript/TypeScript (Web/React/Vue)"
echo "  - React Native (iOS/Android)"
echo "  - Flutter (iOS/Android)"
echo "  - Swift (iOS/macOS)"
echo "  - Kotlin/Java (Android)"
echo
echo "================================= LiveKit Agents ======================"
echo
echo "Voice Agent Status: Running"
echo "Mode: $(if [[ -n "${OPENAI_API_KEY}" ]]; then echo "OpenAI (Cloud)"; else echo "Local (Ollama/Whisper/TTS)"; fi)"
echo
echo "How to use:"
echo "  1. Create LiveKit room via n8n or API"
echo "  2. Generate JWT token with API Key/Secret"
echo "  3. Connect client with token"
echo "  4. Agent joins automatically and responds to voice"
echo
echo "Test Interface: Create file website/voice-test.html"
echo "n8n JWT Generation: Use JavaScript node with jsonwebtoken"
echo
echo "Agent Logs: docker logs livekit-agents -f"
echo "Documentation: https://docs.livekit.io/"
echo "SDK Examples: https://github.com/livekit/livekit-examples"
