#!/bin/bash

set -e

# Source utilities
source "$(dirname "$0")/utils.sh"

# Get script directory
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
PROJECT_ROOT="$( cd "$SCRIPT_DIR/.." &> /dev/null && pwd )"

# Load environment variables
if [ -f "$PROJECT_ROOT/.env" ]; then
    set -a
    source "$PROJECT_ROOT/.env"
    set +a
else
    log_error ".env file not found!"
    exit 1
fi

log_info "Generating Homepage services configuration..."

# Create services.yaml
cat > "$PROJECT_ROOT/homepage_config/services.yaml" << 'EOF'
# Auto-generated Homepage Services Configuration
# Generated by AI LaunchKit

EOF

# Function to add service if active
add_service() {
    local container_name=$1
    local display_name=$2
    local hostname_var=$3
    local icon=$4
    local description=$5
    
    # Check if container is running
    if docker ps --format "{{.Names}}" | grep -q "^${container_name}$"; then
        hostname_value=$(eval echo \$${hostname_var})
        if [ -n "$hostname_value" ]; then
            cat >> "$PROJECT_ROOT/homepage_config/services.yaml" << EOF
    - ${display_name}:
        href: https://${hostname_value}
        icon: ${icon}
        description: ${description}
        
EOF
            log_success "Added ${display_name}"
        fi
    fi
}

# Start with main category
echo "- AI LaunchKit Services:" >> "$PROJECT_ROOT/homepage_config/services.yaml"
echo "" >> "$PROJECT_ROOT/homepage_config/services.yaml"

# Add services based on running containers
add_service "n8n" "n8n" "N8N_HOSTNAME" "n8n.svg" "Workflow Automation"
add_service "flowise" "Flowise" "FLOWISE_HOSTNAME" "si-flowise" "AI Agent Builder"
add_service "bolt" "Bolt.diy" "BOLT_HOSTNAME" "si-bolt" "AI Web Development"
add_service "open-webui" "Open WebUI" "WEBUI_HOSTNAME" "si-openai" "Chat Interface"
add_service "dify" "Dify" "DIFY_HOSTNAME" "si-dify" "AI Apps Platform"

# Development Tools
echo "" >> "$PROJECT_ROOT/homepage_config/services.yaml"
echo "- Development Tools:" >> "$PROJECT_ROOT/homepage_config/services.yaml"
echo "" >> "$PROJECT_ROOT/homepage_config/services.yaml"
add_service "gitea" "Gitea" "GITEA_HOSTNAME" "gitea.svg" "Git Server"
add_service "portainer" "Portainer" "PORTAINER_HOSTNAME" "portainer.svg" "Docker Management"

# Documentation & Knowledge
echo "" >> "$PROJECT_ROOT/homepage_config/services.yaml"
echo "- Documentation & Knowledge:" >> "$PROJECT_ROOT/homepage_config/services.yaml"
echo "" >> "$PROJECT_ROOT/homepage_config/services.yaml"
add_service "outline" "Outline" "OUTLINE_HOSTNAME" "outline.svg" "Team Wiki"
add_service "paperless-ngx" "Paperless" "PAPERLESS_HOSTNAME" "si-paperless" "Document Management"
add_service "seafile" "Seafile" "SEAFILE_HOSTNAME" "si-seafile" "File Sync & Share"
add_service "opennotebook" "Open Notebook" "OPENNOTEBOOK_HOSTNAME" "si-notebook" "AI Knowledge Base"

# Business & Productivity
echo "" >> "$PROJECT_ROOT/homepage_config/services.yaml"
echo "- Business & Productivity:" >> "$PROJECT_ROOT/homepage_config/services.yaml"
echo "" >> "$PROJECT_ROOT/homepage_config/services.yaml"
add_service "docuseal" "DocuSeal" "DOCUSEAL_HOSTNAME" "si-docusign" "E-Signatures"
add_service "calcom" "Cal.com" "CALCOM_HOSTNAME" "si-calendly" "Scheduling"
add_service "twenty-crm" "Twenty CRM" "TWENTY_CRM_HOSTNAME" "si-salesforce" "Customer Management"
add_service "espocrm" "EspoCRM" "ESPOCRM_HOSTNAME" "si-hubspot" "Full CRM Suite"
add_service "odoo" "Odoo" "ODOO_HOSTNAME" "si-odoo" "ERP System"
add_service "vikunja" "Vikunja" "VIKUNJA_HOSTNAME" "vikunja.svg" "Task Management"
add_service "leantime" "Leantime" "LEANTIME_HOSTNAME" "si-asana" "Project Management"
add_service "kimai" "Kimai" "KIMAI_HOSTNAME" "si-clockify" "Time Tracking"
add_service "invoiceninja" "Invoice Ninja" "INVOICENINJA_HOSTNAME" "si-quickbooks" "Invoicing"
add_service "baserow" "Baserow" "BASEROW_HOSTNAME" "si-airtable" "Database"
add_service "nocodb" "NocoDB" "NOCODB_HOSTNAME" "si-airtable" "Smart Spreadsheet"
add_service "formbricks" "Formbricks" "FORMBRICKS_HOSTNAME" "si-typeform" "Surveys"
add_service "metabase" "Metabase" "METABASE_HOSTNAME" "metabase.svg" "Analytics"

# Communication
echo "" >> "$PROJECT_ROOT/homepage_config/services.yaml"
echo "- Communication & Meetings:" >> "$PROJECT_ROOT/homepage_config/services.yaml"
echo "" >> "$PROJECT_ROOT/homepage_config/services.yaml"
add_service "jitsi-web" "Jitsi Meet" "JITSI_HOSTNAME" "si-jitsi" "Video Conferencing"
add_service "postiz" "Postiz" "POSTIZ_HOSTNAME" "si-buffer" "Social Media"
add_service "mautic_web" "Mautic" "MAUTIC_HOSTNAME" "si-mailchimp" "Marketing Automation"

# AI & Research Tools
echo "" >> "$PROJECT_ROOT/homepage_config/services.yaml"
echo "- AI & Research:" >> "$PROJECT_ROOT/homepage_config/services.yaml"
echo "" >> "$PROJECT_ROOT/homepage_config/services.yaml"
add_service "ragapp" "RAGApp" "RAGAPP_HOSTNAME" "si-openai" "RAG Builder"
add_service "perplexica" "Perplexica" "PERPLEXICA_HOSTNAME" "si-perplexity" "AI Search"
add_service "gpt-researcher" "GPT Researcher" "GPTR_HOSTNAME" "si-openai" "Research Agent"
add_service "letta" "Letta" "LETTA_HOSTNAME" "si-robot" "AI Agents"
add_service "comfyui" "ComfyUI" "COMFYUI_HOSTNAME" "si-stablediffusion" "Image Generation"

# Monitoring & Security
echo "" >> "$PROJECT_ROOT/homepage_config/services.yaml"
echo "- System & Security:" >> "$PROJECT_ROOT/homepage_config/services.yaml"
echo "" >> "$PROJECT_ROOT/homepage_config/services.yaml"
add_service "grafana" "Grafana" "GRAFANA_HOSTNAME" "grafana.svg" "Metrics Dashboard"
add_service "prometheus" "Prometheus" "PROMETHEUS_HOSTNAME" "prometheus.svg" "Monitoring"
add_service "uptime-kuma" "Uptime Kuma" "UPTIME_KUMA_HOSTNAME" "uptime-kuma.svg" "Status Monitoring"
add_service "vaultwarden" "Vaultwarden" "VAULTWARDEN_HOSTNAME" "bitwarden.svg" "Password Manager"
add_service "kopia" "Kopia" "KOPIA_HOSTNAME" "si-backblaze" "Backup Solution"

# Infrastructure
echo "" >> "$PROJECT_ROOT/homepage_config/services.yaml"
echo "- Infrastructure:" >> "$PROJECT_ROOT/homepage_config/services.yaml"
echo "" >> "$PROJECT_ROOT/homepage_config/services.yaml"
add_service "supabase-studio" "Supabase" "SUPABASE_HOSTNAME" "supabase.svg" "Backend as Service"
add_service "mailpit" "Mailpit" "MAILPIT_HOSTNAME" "si-mailtrap" "Mail Catcher"
add_service "searxng" "SearXNG" "SEARXNG_HOSTNAME" "searx.svg" "Private Search"
add_service "airbyte-webapp" "Airbyte" "AIRBYTE_HOSTNAME" "si-databricks" "Data Integration"

# Add Docker stats widget at the end
cat >> "$PROJECT_ROOT/homepage_config/services.yaml" << 'EOF'

- System Status:
    - Docker:
        widget:
          type: docker
          container: homepage
          server: docker-socket
EOF

# Create widgets.yaml
cat > "$PROJECT_ROOT/homepage_config/widgets.yaml" << 'EOF'
# System resource widgets
- resources:
    cpu: true
    memory: true
    disk: /

# Search widget
- search:
    provider: searxng
    focus: false
    target: _blank

# Docker integration
- docker:
    type: docker
    socket: /var/run/docker.sock
EOF

# Create docker.yaml for container stats
cat > "$PROJECT_ROOT/homepage_config/docker.yaml" << 'EOF'
docker-socket:
  socket: /var/run/docker.sock
EOF

log_success "Homepage configuration generated successfully!"
log_info "Restarting Homepage to apply changes..."

# Restart Homepage if it's running
if docker ps | grep -q homepage; then
    docker compose -p localai restart homepage
    log_success "Homepage restarted with new configuration"
else
    log_info "Homepage container not running - start it to see the dashboard"
fi
